name: Close stale issues and PRs

on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 365
          days-before-pr-stale: 90
          days-before-issue-close: 7
          days-before-pr-close: 7
          stale-issue-label: "Stale"
          stale-pr-label: "Stale"
          exempt-issue-labels: "Bug,Enhancement,Accepted,NotOurBug,Upstream"
          exempt-pr-labels: "release"
          operations-per-run: 100
